language: ruby
cache: bundler
addons:
  postgresql: '10'
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - AWS_REGION=ap-southeast-1
  - PGPORT=5433
  - CC_TEST_REPORTER_ID=0d3f29fe1c737e27dcc5b679ddf2af93ddcbe3cf42f4b78cfe3324ba9270b545
  - CODECOV_TOKEN="2aaec902-1e35-4664-aa6c-6f1ace7bb77d"
  # AWS Credentials
  - secure: hRqqVSAfPRSF4d6dmn8y2Z7UnWp2pslpKKDuX7RWXvYU6EHiAMwV3W4iss5fUI8bdFcBdtmVoQ4m4tbsC7rYjF5sQqgCUzxsBa0MhptKkgyOEl/eCiteDEX4g25GpM35v75e6irmlJu8oiuKzGTFY7dfaRyYqVREYN3v7Po2HqSgGMqW1eCzJG3rF3TQdx7EzwaWfvd+Mh7zQ1dsmI6AWnTs850VuVUSmnLIfxyVfSw+i6vPfaO9DWiQ06GjEeeIV9HTvfdLxEx31Rw61ia4s2FfPaoGqs5c7oj1qg4Do4anWZx4e0o8R82ze+TWJ4BwYtw4qKRO9mWKZmoaNyLsA9oTLXdnxo81eOQYdOFlBDEgWkuNDHmGOPfdH0asDaraKO4v0No2aKxFHToNRlMJTwzc7Nn8kOF0nR/PAo7T4cu8NSP+GUWS8Twis7XQ5a8aGO5xufVtLA5CeRsUndE3Mr45a7c9c6cLlo/pCG6yn3u0g7b07f+0bYCflzmdpulYK1yhkE7fBaQKOtbOnsqgajCfrENxqeSgFxCPts2rXc1g/g6ZEnGnw2hT/9fye55WzlxZkT4hqpgAAuL6so8WGgxBz288uu0N6W1NVtyzhCfB5y8aOEZHveW1Bz6IL6qsmRrowy3mWXCAgBTLW/E2T7JD1wRoXo+9KMBt8sgtTrk=
before_install:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- gem install bundler
before_script:
- psql -c 'create database twilreapi_test;' -U travis
- "./cc-test-reporter before-build"
after_success:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
deploy:
- provider: elasticbeanstalk
  region: ap-southeast-1
  app: somleng-twilreapi
  env: somleng-twilreapi-webserver
  bucket_name: deploy.somleng.org
  on:
    branch: master
- provider: elasticbeanstalk
  region: ap-southeast-1
  app: somleng-twilreapi
  env: somleng-twilreapi-worker
  bucket_name: deploy.somleng.org
  on:
    branch: master
- provider: elasticbeanstalk
  region: ap-southeast-1
  app: somleng-twilreapi
  env: somleng-twilreapi-caller-worker
  bucket_name: deploy.somleng.org
  on:
    branch: master
