language: ruby
sudo: false
services:
  - postgresql
env:
  global:
    - START_SIMPLECOV=1
addons:
  postgresql: '9.6'
  code_climate:
    repo_token:
      secure: "ixvE5zOUySIHsUCLWjuoDqikwjW9yHERucrouHRw6TMLZHdMw2dLtHoANOJblSNvQ/RY+w1qNEX7wUgKbjoy7MfxZauNSFzoiCBejrsSyXSGtopIdUZilRyPP8OPS2f4RBlTf5pNX1iFay1UEM+o38NyOW68LTaQahJ9pUjGDsljdqQcZJSX6NxZ3HiY4shyetzeA3zlC+31GG02hd44zsvh05oRJrlT0wAa6PrzmAc0hHWWDhCCe/yN+JQyM5Ac+vFq7/uDUkrpj4dWKauZfpxk7kdU+QmtSEW+qeC65C9kCRxWqSKlqfhPs8WZjy//gQ5dk1Y7asq+fwvoBU9j90XI+31++TX8HB7Yb2U3wYleLJIE9bYIsnwFAv0gp5KuX65Zaw64xEvH6wmiDXDFYmktiFInUz4skk26zjB/7n3wCrVPD5ZbzXIzD0STb+BHwoRkMdYjfCuUmG1YpOOHZiOt8kaiE2413GuvD8C5UYoyltJzkPHAcwf2f6rqa1+trRn+1GwlppICQodgkMHE3Gv5QVy0Lm+7l+7qQ2zOvqWU2UjjYKeFR17MFgZ+xZ6bP6rkm8pl5OleT6p1fpJzclSEn5SMxM0xQgu5Uw5gtHIB82bJkzuACaecpGo0HkC/JJ9/MJ9FZspiFLGttGq1cdbCK37iw50ynB4GN05U2Y0="
before_script:
  - psql -c 'create database twilreapi_test;' -U postgres
  - psql -U postgres -c "create extension pgcrypto"
after_success:
  - bundle exec codeclimate-test-reporter
